server:
  port: 8080

spring:
  application:
    name: rik-exercise-be

  h2:
    console:
      enabled: true
      path: /h2

  datasource:
    url: jdbc:h2:mem:~/test;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driver-class-name: org.h2.Driver
    platform: h2
    hikari:
      minimum-idle: 1
      maximum-pool-size: 5

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    #      ddl-auto: update
    properties:
      hibernate:
        show_sql: false
        use_sql_comments: false
        format_sql: false
        generate_statistics: false
